# Generated by Django 4.2 on 2023-04-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_plan_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('Basci', 'Basci'), ('p1', 'plan1'), ('p2', 'plan2')], max_length=20, unique=True),
        ),
    ]
