# Generated by Django 4.2 on 2023-04-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_subscription_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=150)),
                ('img_tender', models.ImageField(upload_to='tender/')),
                ('end_time', models.DateTimeField()),
                ('state', models.CharField(max_length=150)),
                ('sectoer', models.CharField(choices=[('sc1', 'sc1'), ('sc2', 'sc2'), ('sc3', 'sc3'), ('sc4', 'sc4'), ('sc5', 'sc5')], max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('Basci', 'Basci'), ('p1', 'plan1'), ('p2', 'plan2'), ('p3', 'plan3')], max_length=20, unique=True),
        ),
    ]
