# Generated by Django 4.2 on 2023-04-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tender_alter_subscription_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sc1', 'sc1'), ('sc2', 'sc2'), ('sc3', 'sc3'), ('sc4', 'sc4'), ('sc5', 'sc5')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='tender',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='tender',
            name='sectoer',
        ),
        migrations.AddField(
            model_name='tender',
            name='sectoer',
            field=models.ManyToManyField(to='accounts.choice'),
        ),
    ]
