# Generated by Django 4.2 on 2023-04-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tender_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('sc1', 'sc1'), ('sc2', 'sc2'), ('sc3', 'sc3'), ('sc4', 'sc4'), ('sc5', 'sc5')], max_length=20, unique=True),
        ),
    ]
