# Generated by Django 4.2 on 2023-04-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_subscription_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.AlterField(
            model_name='tender',
            name='activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ManyToManyField(to='accounts.choice'),
        ),
    ]
