# Generated by Django 4.2 on 2023-04-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_subscription_plan_alter_tender_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='tittle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
