# Generated by Django 4.2 on 2023-05-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='img_tender',
        ),
    ]
