# Generated by Django 4.2 on 2023-05-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_tender_img_tender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='name',
            field=models.CharField(choices=[('studies', 'studies ')], max_length=50),
        ),
    ]
