# Generated by Django 4.2 on 2023-05-23 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_choice_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivetender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField()),
                ('state', models.CharField(max_length=150)),
                ('activity', models.BooleanField(default=False)),
                ('sectoer', models.ManyToManyField(to='accounts.choice')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='tender/')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.archivetender')),
            ],
        ),
    ]
