# Generated by Django 4.2 on 2023-05-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_file_archivefile_archive_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='tittle_ar',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
