# Generated by Django 4.2 on 2023-06-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_tender_city_tender_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tender',
            name='type_name',
        ),
        migrations.AddField(
            model_name='tender',
            name='type_Name',
            field=models.ManyToManyField(to='accounts.type_tender'),
        ),
    ]
