# Generated by Django 4.2 on 2023-06-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_type_tender_remove_tender_type_name_tender_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_tender',
            name='type_name',
            field=models.CharField(blank=True, choices=[('Limited national tenders', 'Limited national tenders'), ('Open national tenders', 'Open national tenders'), ('limited international tenders', 'limited international tenders'), ('Open international tenders', 'Open international tenders'), ('Limited national tenders', 'Limited national tenders'), ('Open national tenders', 'Open national tenders'), ('Limited international consulting', 'Limited international consulting'), ('Open international consultation', 'Open international consultation'), ('Open national competition', 'Open national competition'), ('Limited National Competition', 'Limited National Competition'), ('Open national tenders', 'Open national tenders'), ('limited international tenders', 'limited international tenders'), ('Notice of qualification', 'Notice of qualification'), ('Limited advance national notice', 'LLimited advance national notice'), ('Advance national notice', 'Advance national notice'), ('Limited advance national and international notice', 'Limited advance national and international notice'), ('Extending the deadlines for the limited national tender', 'Extending the deadlines for the limited national tender'), ('Extending the deadlines for the national open tender', 'Extending the deadlines for the national open tender'), ('Extending the deadlines for the limited international tender', 'Extending the deadlines for the limited international tender'), ('Extension of deadlines for open international tender', 'Extension of deadlines for open international tender'), ('Extending the deadlines for the limited national and international tender', 'Extending the deadlines for the limited national and international tender'), ('Extending the deadlines for the national and international open tender', 'Extending the deadlines for the national and international open tender'), ('Express interest', 'Express interest')], max_length=150, null=True),
        ),
    ]
